FROM php:7.2-apache

# Download packets for compiling
RUN apt-get update && apt-get install -y libz-dev zlib1g-dev libpng-dev

# Install modules
# zib
RUN docker-php-ext-install zlib
# gd
RUN docker-php-ext-install zlib
# Mysql
RUN docker-php-ext-install pdo_mysql

EXPOSE 80
CMD ["apache2-foreground"]
